### ISSUE TITLE
error when make

### ISSUE THREAD

**Issue by thelongestusernameofall** [sebastiencs/Packer_ELF#1]
root@iZ23hcrwyqhZ:/research/elfpacker/elfpacker/Packer_ELF-master# make
gcc -Wall -Wextra -std=c99 -I ./includes   -c -o src/packer.o src/packer.c
gcc -Wall -Wextra -std=c99 -I ./includes   -c -o src/cypher_code.o src/cypher_code.c
src/cypher_code.c: In function ‘get_random_key’:
src/cypher_code.c:33:11: error: ‘__NR_getrandom’ undeclared (first use in this function)
   syscall(__NR_getrandom, &key, 8, 0);
           ^
src/cypher_code.c:33:11: note: each undeclared identifier is reported only once for each function it appears in
make: **\* [src/cypher_code.o] Error 1

**Comment by sebastiencs** [comment]
What is your kernel version ?
It uses the syscall [getrandom()](http://man7.org/linux/man-pages/man2/getrandom.2.html) avalaible since kernel 3.17 to generate a random key.

**Comment by thelongestusernameofall** [comment]
thank you very much for your reply.

root@iZ23hcrwyqhZ:~# uname -a
Linux iZ23hcrwyqhZ 3.13.0-80-generic #124-Ubuntu SMP Tue Feb 23 02:22:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

It's ubuntu 64bit, with latest updates.

**Comment by thelongestusernameofall** [comment]
The problem has been solved. By updating my ubuntu from 14.04 to 16.04, and the kernel was updated from 3.13 to 4.4.0.

Thank you very much.
